export const metadata = {
    title: 'Profile | new site',
    description: 'Generated by create next app',
  }

const ProfilePage = () => {
    return (
        <div>
            profile page
        </div>
    );
};

export default ProfilePage;