import Link from "next/link";

export const metadata = {
    title: 'Blogs | new site',
    description: 'Generated by create next app',
  }

  const blogLink = [
    {
        id: 1,
        year: 2016,
        title: 'title 1',
    },
    {
        id: 2,
        year: 2017,
        title: 'title 2',
    },
    {
        id: 3,
        year: 2018,
        title: 'title 3',
    },
    {
        id: 4,
        year: 2019,
        title: 'title 4',
    },
    {
        id: 5,
        year: 2020,
        title: 'title 5',
    },
  ]


const BlogsPage = () => {
    return (
        <>
            <div className="container mx-auto">
                {
                    blogLink.map(({id, year, title}) => <Link className="border-purple-700 border-2 block mt-3" key={id} href={{
                        pathname : `/blogs/${year}/${id}`,
                        query: {
                            title : title,
                        }
                    }}>
                    {title}
                    </Link>)
                }
            </div>
        </>
    );
};

export default BlogsPage;