export const metadata = {
    title: 'Add to cart | Dashboard | new site',
    description: 'Generated by create next app',
}

const AddToCart = () => {
    return (
        <div>
            AddToCart
        </div>
    );
};

export default AddToCart;