export const metadata = {
    title: 'Add Product | Dashboard | new site',
    description: 'Generated by create next app',
}

const AddProduct = () => {
    return (
        <div>
            add product
        </div>
    );
};

export default AddProduct;