
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'new site',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  console.log('form RootLayout')
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {children}
      
        </body>
    </html>
  )
}
