export const metadata = {
    title: 'manage product | Dashboard | new site',
    description: 'Generated by create next app',
}

const ManageProduct = () => {
    return (
        <div>
            ManageProduct
        </div>
    );
};

export default ManageProduct;