import Sidebar from "./Sidebar";

export const metadata = {
    title: 'Dashboard | new site',
    description: 'Generated by create next app',
  }

const DashboardLayout = ({children}) => {
    return (
        <div className="flex">
            <Sidebar></Sidebar>
            {children}
        </div>
    );
};

export default DashboardLayout;