export const metadata = {
    title: 'contact | new site',
    description: 'Generated by create next app',
  }

const ContactPage = () => {
    return (
        <div>
            ContactPage
        </div>
    );
};

export default ContactPage;